---
Title: "Intro to Categorical Model-Making Module by Austin Hayes"

Author:
  - Name: Austin Hayes

  -  Email: ahayes65@charlotte.edu

  -  Affiliation: University of North Carolina at Charlotte

Date: July 29, 2025

Description: Using WNBA Team 'Per Game' stats, we will review the basics of categorical model-making. We will make QDA, LDA and Logistic models in order to predict which team will become the next WNBA Champion.

Categories:
  - Logistic Regression
  - Quadratic Discriminant Analysis
  - Linear Discriminant Analysis
  - Importing and Reading data
  - Data Cleaning
  - Data Science
  - Pandas


### Data

This Dataset is from Basketball Reference @ https://www.basketball-reference.com

Visit the original data page here: https://www.basketball-reference.com/wnba/years/2024.html

The data set contains 60 rows and 26 columns. Each row represents a WNBA team during the 2024 season.

Download data: 

Available on the [Intro to Categorical Model-Making Module by Austin Hayes](https://github.com/schuckers/Charlotte_SCORE_Summer25/tree/main/Data%20for%20Modules/Data%20For%20Intro%20to%20Categorical%20Model-Making%20Module%20by%20Austin%20Hayes): [2024_WNBA_Per_Game.csv](https://raw.githubusercontent.com/schuckers/Charlotte_SCORE_Summer25/refs/heads/main/Data%20for%20Modules/Data%20For%20Intro%20to%20Categorical%20Model-Making%20Module%20by%20Austin%20Hayes/2024_WNBA_Per_Game.csv)

---

### Variables and their Descriptions:


<details>
<summary><b>Variable Descriptions</b></summary>

| Variable | Description |
|----------|-------------|
| Rk       | Rank of the team in the league |
| Team     | Name of the team |
| G        | Games played |
| MP       | Minutes played per game |
| FG       | Field Goals made per game |
| FGA      | Field Goal attempts per game |
| FG%      | Field Goal percentage (FG ÷ FGA) |
| 3P       | Three-Point Field Goals made per game |
| 3PA      | Three-Point Field Goal attempts per game |
| 3P%      | Three-Point Field Goal percentage (3P ÷ 3PA) |
| 2P       | Two-Point Field Goals made per game |
| 2PA      | Two-Point Field Goal attempts per game |
| 2P%      | Two-Point Field Goal percentage (2P ÷ 2PA) |
| FT       | Free Throws made per game |
| FTA      | Free Throw attempts per game |
| FT%      | Free Throw percentage (FT ÷ FTA) |
| ORB      | Offensive Rebounds per game |
| DRB      | Defensive Rebounds per game |
| TRB      | Total Rebounds per game |
| AST      | Assists per game |
| STL      | Steals per game |
| BLK      | Blocks per game |
| TOV      | Turnovers per game |
| PF       | Personal Fouls per game |
| PTS      | Points scored per game |
| CHAMPION | Did that team win the championship that year? 1 = Yes, 0 = No |

</details>

---

# Learning Goals

- Learn about the basics of categorical modeling
- Compare and contrast models using statistical metrics
- Learn about Quadratic Discriminant Analysis
- Learn about Linear Discriminant Analysis
- Learn about Logistic Regression

---

# Getting Started


In this lesson, we will learn about categorical modeling in order to predict the outcome of a certain event based on past and current metrics. 

Today, we will be predicting what team will be the WNBA champion this year! Before we get started, we need to import certain librarys in order to achieve this goal.

If you don't have any of these librarys downloaded, you can learn about how to do so with the following links:

Pandas: https://pandas.pydata.org/docs/getting_started/install.html 

Numpy: https://numpy.org/install/

Sci-Kit Learn: https://scikit-learn.org/stable/install.html

After downloading those librarys, let's import them.

In [25]:
# Import the necessary librarys for the module
# Basic Data Science Library for importing data and data manipulation
import pandas as pd

# Library for mathematical operations
import numpy as np

# Import only the necessary functions from the sklearn library
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis

---

# Categorical Modeling

Categorical Modeling is a way of measuring/predicting a non-numeric outcome using previously available data. For today, we will be predicting a binary outcome, like 'yes' or 'no', 'Champion' or 'Not Champion', etc. There are various models that can be used to achieve this but today we will go over Logistic, LDA and QDA models. Each of these models use different methodologies to achieve the same goal. Therefore, each models predictions may differ from each other, warranting comparison. This can be done using certain metrics that we will go over later in this lesson.

---

# Modeling Process For This Module

In order to build a model, we will need to train the model and then test the model to see how accurate it is. Normally, we would want to build the model by splitting a season's worth of data into a train dataset and a test dataset. You want to split the data into a higher ratio of training data than test data. This ensures that the model will be more adequately prepared to make predicitions on the test data. On the flip side, there needs to be a balance between your train and test sets because the more test data you have, the more data you have to test your models accuracy. Normally, I use 60-70% of the data for training the model and 40-30% for testing the model.

However, we will want to do something a little different in this module. For the seasons we will be training the model with, there are only 12 WNBA teams. That is not enough data! In this case, I have compiled a dataset of 'Per Game' data for every team over the last 5 seasons, before the 2024 season. 'Per Game' means that the stats are an average of each catgory among all games played. For example, the 'PTS' column is an average of each teams points scored per game. We will train our models on that compiled dataset and then test the accuracy of our models with the 2024 season data. After reviewing each model's accuracy score, we will pick the model with highest accuracy and re-train it with another compiled dataset. This other compiled dataset will include 2020-2024 data instead of 2019-2023 in order to provide the newest data to the model. After retraining the model, we will have the model predict the next WNBA Champion.

NOTE: The compiled dataset was built upon several 'Per Game' datasets from Basketball-Reference.com. Please visit their website using the link at the top of this module. Each teams name has been edited to identify what year each team's stats are from since there are reoccuring team names. A champion column was also added in order to identify which teams won a championship. 1 = Champions, 0 = Not Champions

In order to test the accuracy of the model(s) amongst one another, we want to train the model(s) on the previous 5 season's worth of data. Since this is a special case (only one 'champion' and NOT multiple) we will train the model(s) using 2019-2023 season data and test it with the 2024 season data. The model with the highest accuracy, or of our choosing, will be used to predict who the WNBA champion will be this season using the 'Per Game' stats thus far.

To summarize, a model is something we can train with data so it can make a prediction on new data.

# Importing data and making train/test sets

Let's get started by reading in the data.

In [26]:
# Read in the WNBA 2019-2023 data from Github
# This dataset will be used to train the intial models
TRAIN_WNBA_19_23_Data = pd.read_csv('https://raw.githubusercontent.com/schuckers/Charlotte_SCORE_Summer25/refs/heads/main/Data%20for%20Modules/Data%20For%20Intro%20to%20Categorical%20Model-Making%20Module%20by%20Austin%20Hayes/WNBA_PER_GAME_19_23_DATA.csv')

In [27]:
# Read in the WNBA 2024 data from Github
# This will be used to test the intial models 
TEST_WNBA_2024_Data = pd.read_csv('https://raw.githubusercontent.com/schuckers/Charlotte_SCORE_Summer25/refs/heads/main/Data%20for%20Modules/Data%20For%20Intro%20to%20Categorical%20Model-Making%20Module%20by%20Austin%20Hayes/2024_WNBA_Per_Game.csv')

In [28]:
# Read in the WNBA 2020-2024 data from Github 
# This dataset will be used to train the final model
TRAIN_WNBA_20_24_Data = pd.read_csv('https://raw.githubusercontent.com/schuckers/Charlotte_SCORE_Summer25/refs/heads/main/Data%20for%20Modules/Data%20For%20Intro%20to%20Categorical%20Model-Making%20Module%20by%20Austin%20Hayes/WNBA_PER_GAME_20_24_DATA.csv')

In [29]:
# Read in the current WNBA 2025 stats for our model prediction later on in this module
CURRENT_WNBA_2025_Data = pd.read_csv('https://raw.githubusercontent.com/schuckers/Charlotte_SCORE_Summer25/refs/heads/main/Data%20for%20Modules/Data%20For%20Intro%20to%20Categorical%20Model-Making%20Module%20by%20Austin%20Hayes/2025_WNBA_Per_Game.csv')

---

# Logistic Regression

Logistic Regression is a categorical model that uses probabilities to predict a binary outcome. It assumes a linear relationship between independent variables. Let's go ahead and establish a logistic model and train it with the compiled 2019-2023 data.

We will train it ONLY using the neccesary stats. The model also needs to be trained using integer values, so let's keep it simple by predicting the champion based on the following stats: FG, FGA, 3P, 3PA, 2P, 2PA, FT, FTA, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS. The definitions of these variables can be found at the top of this module. 

In [30]:
# Create the logistic regression model
logistic_model = LogisticRegression()

# Train the model using the 2023 WNBA data
logistic_model.fit(TRAIN_WNBA_19_23_Data[['FG', 'FGA', '3P', '3PA', '2P', '2PA', 'FT', 'FTA', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']], TRAIN_WNBA_19_23_Data['CHAMPION'])

C:\Users\ajhay\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [31]:
# Have the model make predictions using the 2024 WNBA data
logistic_model.predict(TEST_WNBA_2024_Data[['FG', 'FGA', '3P', '3PA', '2P', '2PA', 'FT', 'FTA', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']])

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

MMHHHMMM... very interesting! The model predicted the Las Vegas Aces as the 2024 WNBA Champions! Unfortunately, that is incorrect because the New York Liberty won the championship that season. Let's take a look at the probabilities of winning the championship based on their per game stats.

In [32]:
# Have the model show the probabilities of each team winning the championship
logistic_model.predict_proba(TEST_WNBA_2024_Data[['FG', 'FGA', '3P', '3PA', '2P', '2PA', 'FT', 'FTA', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']])

array([[3.71432789e-01, 6.28567211e-01],
       [8.31635636e-01, 1.68364364e-01],
       [9.85703709e-01, 1.42962908e-02],
       [9.95280087e-01, 4.71991277e-03],
       [9.17706119e-01, 8.22938811e-02],
       [8.50089387e-01, 1.49910613e-01],
       [9.51951204e-01, 4.80487964e-02],
       [9.57010729e-01, 4.29892711e-02],
       [9.87847915e-01, 1.21520854e-02],
       [9.98185367e-01, 1.81463299e-03],
       [9.99438912e-01, 5.61087973e-04],
       [9.98752987e-01, 1.24701304e-03]])

The probabilities on the left are for 0 and the right is for 1. Remember, these probabilities are in a rounded format so you can indicate where they actually are beyond the decimal point by looking at the number beyond the hyphen. We can see that the model predicted the first team in the list to have the highest odds to win the championship. The model made this decision because the predicted odds were above 50%. However, looking back at the data, the second team in the data won the championship in 2024, that team being the New York Liberty. Therefore, the second team should have the highest odds for us to feel better about this model.

Logistic regression assumes a linear relationship in the data so this may indicate that this is a poor type of model to use for this situation. For now, let's go ahead and calculate an accuracy score and move on to Discriminant Analysis Models. 

In [33]:
TEST_WNBA_2024_Data

Rk                Team   G     MP    FG   FGA    FG%    3P   3PA    3P%  \
0    1      Las Vegas Aces  40  200.6  30.9  68.1  0.454   9.4  26.5  0.355   
1    2    New York Liberty  40  200.0  30.8  68.7  0.448  10.1  29.0  0.349   
2    3       Indiana Fever  40  200.6  31.3  68.5  0.456   9.2  25.9  0.356   
3    4        Dallas Wings  40  201.9  31.7  71.0  0.446   6.3  19.2  0.326   
4    5       Seattle Storm  40  201.2  31.1  71.3  0.435   6.1  21.0  0.288   
5    6      Minnesota Lynx  40  201.9  30.1  67.3  0.448   9.5  25.0  0.380   
6    7     Phoenix Mercury  40  201.2  29.1  66.3  0.439   8.5  26.2  0.326   
7    8     Connecticut Sun  40  201.2  29.3  65.9  0.444   5.9  18.0  0.327   
8    9  Washington Mystics  40  201.2  29.0  67.0  0.433   9.7  26.6  0.366   
9   10  Los Angeles Sparks  40  200.6  28.1  66.4  0.423   7.2  22.6  0.320   
10  11         Chicago Sky  40  200.0  29.7  70.3  0.422   4.8  14.9  0.323   
11  12       Atlanta Dream  40  201.9  27.8  68.1  0.408   6.0  19.4  0.308   

    ...   ORB   DRB   TRB   AST  STL  BLK   TOV    PF   PTS  CHAMPION  
0   ...   5.6  28.5  34.1  20.5  7.1  5.0  10.8  16.5  86.4         0  
1   ...   8.5  28.1  36.6  22.8  7.9  4.5  12.7  15.4  85.6         1  
2   ...   8.3  26.8  35.1  20.4  5.9  4.3  14.2  18.2  85.0         0  
3   ...  10.5  24.3  34.8  20.4  7.1  4.0  14.8  18.5  84.2         0  
4   ...   8.7  26.0  34.7  20.7  9.3  5.2  12.4  16.5  83.2         0  
5   ...   7.4  26.8  34.3  23.0  8.6  4.2  13.4  16.4  82.0         0  
6   ...   6.7  25.6  32.3  19.9  6.6  4.7  13.3  16.9  81.5         0  
7   ...   8.4  25.1  33.5  19.9  8.2  3.7  12.1  16.1  80.1         0  
8   ...   7.1  24.8  31.9  21.6  7.3  3.4  15.1  18.4  79.3         0  
9   ...   7.4  25.3  32.7  19.7  7.3  3.2  15.0  17.9  78.4         0  
10  ...  10.9  25.8  36.6  19.0  7.0  3.8  13.1  19.0  77.4         0  
11  ...   9.2  26.9  36.1  18.4  7.2  3.7  12.5  16.9  77.0         0  

[12 rows x 26 columns]

In [44]:
# Make accuracy score
accuracy_score_log = accuracy_score(TEST_WNBA_2024_Data['CHAMPION'], logistic_model.predict(TEST_WNBA_2024_Data[['FG', 'FGA', '3P', '3PA', '2P', '2PA', 'FT', 'FTA', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']]))

In [45]:
# Print the accuracy score
print(f"Accuracy Score: {accuracy_score}")

Accuracy Score: <function accuracy_score at 0x0000019337BA13A0>


---

# Discriminant Analysis


There are 2 types of Discriminant Analysis Models that we will be going over in this lesson. One is called Linear Discriminat Analysis (LDA) and the other being Quadratic Discriminant Analysis (QDA). These models essentially create a line of best fit to classify data points into a category. Discriminant Analysis finds the best combination of features through variance analysis. We will begin with LDA first.

--- 

# Linear Discriminant Analysis


LDA is a linear form of discriminant analysis and it assumes that each group follows a normal distribution. It also assumes that the variance for each classification group is the same. This means that the variance(s) between champion and non-champion is the same. Let's get started; we will follow the EXACT same process as we did with logistic regression.

In [36]:
# Create the Linear Discriminant Analysis model
lda_model = LinearDiscriminantAnalysis()

# Train the model using the 2023 WNBA data
lda_model.fit(TRAIN_WNBA_19_23_Data[['FG', 'FGA', '3P', '3PA', '2P', '2PA', 'FT', 'FTA', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']], TRAIN_WNBA_19_23_Data['CHAMPION'])

LinearDiscriminantAnalysis()

In [37]:
# Now let's test the model using the 2024 WNBA data and have it make predictions
lda_model.predict(TEST_WNBA_2024_Data[['FG', 'FGA', '3P', '3PA', '2P', '2PA', 'FT', 'FTA', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']])

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

Interesting; this LDA model produced the same result when compared to the logistic model. Unfortunately, that makes this result incorrect. Let's take a look at the probability breakdown.

In [ ]:
# Predict the probabilities of each team winning the championship
lda_model.predict_proba(TEST_WNBA_2024_Data[['FG', 'FGA', '3P', '3PA', '2P', '2PA', 'FT', 'FTA', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']])

array([[4.73959663e-01, 5.26040337e-01],
       [9.20512083e-01, 7.94879165e-02],
       [9.99931470e-01, 6.85296213e-05],
       [9.99991369e-01, 8.63117672e-06],
       [9.85512568e-01, 1.44874323e-02],
       [9.82301913e-01, 1.76980869e-02],
       [9.83625105e-01, 1.63748947e-02],
       [9.99994256e-01, 5.74396085e-06],
       [9.98548189e-01, 1.45181125e-03],
       [9.99986176e-01, 1.38236852e-05],
       [9.99993913e-01, 6.08740301e-06],
       [9.99985822e-01, 1.41784680e-05]])

WOW! It looks like there is not one other team that REMOTELY competes with the Ace's probability to win the championship, according to this model. Although both models had the same end result, these probabilities are quite different from that of the logistic model. Let's record the accuracy score and move onto QDA.

In [39]:
# Assign LDA Model Prediction from 2024 WNBA Data to a variable
lda_predictions = lda_model.predict(TEST_WNBA_2024_Data[['FG', 'FGA', '3P', '3PA', '2P', '2PA', 'FT', 'FTA', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']])
lda_predictions

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [46]:
# Get Accuracy Score
accuracy_score_lda = accuracy_score(TEST_WNBA_2024_Data['CHAMPION'], lda_predictions)

# Print the accuracy score
print(f"Accuracy Score: {accuracy_score_lda}")

Accuracy Score: 0.8333333333333334


---

# Quadratic Disciminant Analysis

QDA is very similar to LDA. QDA, like LDA, assumes a normal distribution. Unlike LDA, QDA allows each classification group to have different variances. QDA does NOT assume a linear classification boundary so it is seen as a flexible option in comparison. Now Let's get started.

NOTE: Before we get started, QDA is a bit different and needs more than one sample in the champion category. In other words, we need to add another row that has 1 under the champion column. This get's a bit hairy since we only want to include teams in the present. However, lets go ahead and do the following: Combine the 2022 and 2023 datasets.

In [41]:
# Make the Quadratic Discriminant Analysis model
qda_model = QuadraticDiscriminantAnalysis()

# Train the model using the 2023 WNBA data
qda_model.fit(TRAIN_WNBA_19_23_Data[['FG', 'FGA', '3P', '3PA', '2P', '2PA', 'FT', 'FTA', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']], TRAIN_WNBA_19_23_Data['CHAMPION'])

C:\Users\ajhay\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\discriminant_analysis.py:947: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


QuadraticDiscriminantAnalysis()

In [42]:
# Have the model make predictions using the 2024 WNBA data
qda_model.predict(TEST_WNBA_2024_Data[['FG', 'FGA', '3P', '3PA', '2P', '2PA', 'FT', 'FTA', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

Very Interesting! This QDA Model predicted none of the teams as WNBA Champs! Let;s take a look at the probability breakdown below.

In [47]:
# Predict the probabilities of each team winning the championship
qda_model.predict_proba(TEST_WNBA_2024_Data[['FG', 'FGA', '3P', '3PA', '2P', '2PA', 'FT', 'FTA', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']])

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

MMMM There might be a massive colinearity issue with using this model! It may be best to skip the use of this model! Let's move onto KNN!