Comments M. Schuckers 11 Aug 2025
- Let's break this first markdown into a couple of cells
- Make sure you mention kNN methods earlier 
- I think there are only 12 rows in these data and that is likely to lead to some overfitting.  Your description says 60 rows which would be 5 years of data, I think.
- Also have a categorical response that is only 8% of rows can lead to some issues.  Can we make the target, made the playoffs instead?  The model can be 92% accurate by just saying all of the rows will be zero.
- For transforming and rescaling data, you should use the scaler for the training data and apply that same scaler to the test data.  This avoids some possible information leakage from the training to the test data.
- When I run the logistic I don't get any 1's.  Just 0's and the probability for the first team is 0.38 of being a one.

---
Title: "Intro to Categorical Model-Making Module by Austin Hayes"

Author:
  - Name: Austin Hayes

  -  Email: ahayes65@charlotte.edu

  -  Affiliation: University of North Carolina at Charlotte

Date: July 29, 2025

Description: Using WNBA Team 'Per Game' stats, we will review the basics of categorical model-making. We will make QDA, LDA, kNN, and Logistic models in order to predict which team will become the next WNBA Champion.

Categories:
  - Logistic Regression
  - Quadratic Discriminant Analysis
  - Linear Discriminant Analysis
  - K Nearest Neighbors
  - Importing and Reading data
  - Data Cleaning
  - Data Science
  - Pandas


### Data

This Dataset is from Basketball Reference @ https://www.basketball-reference.com

Visit the original data page here: https://www.basketball-reference.com/wnba/years/2024.html

The data set contains 60 rows and 26 columns. Each row represents a WNBA team during the 2024 season.

Download data: 

Available on the [Intro to Categorical Model-Making Module by Austin Hayes](https://github.com/schuckers/Charlotte_SCORE_Summer25/tree/main/Data%20for%20Modules/Data%20For%20Intro%20to%20Categorical%20Model-Making%20Module%20by%20Austin%20Hayes): [2024_WNBA_Per_Game.csv](https://raw.githubusercontent.com/schuckers/Charlotte_SCORE_Summer25/refs/heads/main/Data%20for%20Modules/Data%20For%20Intro%20to%20Categorical%20Model-Making%20Module%20by%20Austin%20Hayes/2024_WNBA_Per_Game.csv)

---

### Variables and their Descriptions:


<details>
<summary><b>Variable Descriptions</b></summary>

| Variable | Description |
|----------|-------------|
| Rk       | Rank of the team in the league |
| Team     | Name of the team |
| G        | Games played |
| MP       | Minutes played per game |
| FG       | Field Goals made per game |
| FGA      | Field Goal attempts per game |
| FG%      | Field Goal percentage (FG ÷ FGA) |
| 3P       | Three-Point Field Goals made per game |
| 3PA      | Three-Point Field Goal attempts per game |
| 3P%      | Three-Point Field Goal percentage (3P ÷ 3PA) |
| 2P       | Two-Point Field Goals made per game |
| 2PA      | Two-Point Field Goal attempts per game |
| 2P%      | Two-Point Field Goal percentage (2P ÷ 2PA) |
| FT       | Free Throws made per game |
| FTA      | Free Throw attempts per game |
| FT%      | Free Throw percentage (FT ÷ FTA) |
| ORB      | Offensive Rebounds per game |
| DRB      | Defensive Rebounds per game |
| TRB      | Total Rebounds per game |
| AST      | Assists per game |
| STL      | Steals per game |
| BLK      | Blocks per game |
| TOV      | Turnovers per game |
| PF       | Personal Fouls per game |
| PTS      | Points scored per game |
| CHAMPION | Did that team win the championship that year? 1 = Yes, 0 = No |

</details>

---

# Learning Goals

- Learn about the basics of categorical modeling
- Compare and contrast models using statistical metrics
- Learn about Quadratic Discriminant Analysis
- Learn about Linear Discriminant Analysis
- Learn about Logistic Regression

---

# Getting Started


In this lesson, we will learn about categorical modeling in order to predict the outcome of a certain event based on past and current metrics. 

Today, we will be predicting what team will be the WNBA champion this year! Before we get started, we need to import certain librarys in order to achieve this goal.

If you don't have any of these librarys downloaded, you can learn about how to do so with the following links:

Pandas: https://pandas.pydata.org/docs/getting_started/install.html 

Numpy: https://numpy.org/install/

Sci-Kit Learn: https://scikit-learn.org/stable/install.html

After downloading those librarys, let's import them.

In [1]:
# Import the necessary librarys for the module
# Basic Data Science Library for importing data and data manipulation
import pandas as pd

# Library for mathematical operations
import numpy as np

# Import only the necessary functions from the sklearn library
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

---

# Classfication

Classification is a way of modelling where we try to predict a non-numeric outcome using previously available data. For today, we will be predicting a binary outcome, like 'yes' or 'no', 'Champion' or 'Not Champion', etc. There are various models that can be used to achieve this but today we will go over Logistic, KNN, LDA and QDA models. Each of these models use different methodologies to achieve the same goal. Therefore, each models predictions may differ from each other, warranting comparison. This can be done using certain metrics that we will go over later in this lesson.

---

# Modeling Process For This Module

In order to build a model, we will need to train the model and then test the model to see how accurate it is. Normally, we would want to build the model by splitting a season's worth of data into a train dataset and a test dataset. You want to split the data into a higher ratio of training data than test data. This ensures that the model will be more adequately prepared to make predicitions on the test data. On the flip side, there needs to be a balance between your train and test sets because the more test data you have, the more data you have to test your models accuracy. Normally, we use 60-70% of the data for training the model and 40-30% for testing the model.

However, we will want to do something a little different in this module. For the seasons we will be training the model with, there are only 12 WNBA teams. That is not enough data! In this case, we have compiled a dataset of 'Per Game' data for every team over the last 5 seasons, before the 2024 season. 'Per Game' means that the stats are an average of each catgory among all games played. For example, the 'PTS' column is an average of each teams points scored per game. We will train our models on that compiled dataset and then test the accuracy of our models with the 2024 season data. After reviewing each model's accuracy score, we will pick the model with highest accuracy and re-train it with another compiled dataset. This other compiled dataset will include 2020-2024 data instead of 2019-2023 in order to provide the newest data to the model. After retraining the model, we will have the model predict the next WNBA Champion.

NOTE: The compiled dataset was built upon several 'Per Game' datasets from Basketball-Reference.com. Please visit their website using the link at the top of this module. Each teams name has been edited to identify what year each team's stats are from since there are reoccuring team names. A champion column was also added in order to identify which teams won a championship. 1 = Champions, 0 = Not Champions

In order to test the accuracy of the model(s) amongst one another, we want to train the model(s) on the previous 5 season's worth of data. Since this is a special case (only one 'champion' and NOT multiple) we will train the model(s) using 2019-2023 season data and test it with the 2024 season data. The model with the highest accuracy, or of our choosing, will be used to predict who the WNBA champion will be this season using the 'Per Game' stats thus far.

To summarize, a model is something we can train with data so it can make a prediction on new data.

# Importing data and making train/test sets

Let's get started by reading in the data.

In [2]:
# Read in the WNBA 2019-2023 data from Github
# This dataset will be used to train the intial models
TRAIN_WNBA_19_23_Data = pd.read_csv('https://raw.githubusercontent.com/schuckers/Charlotte_SCORE_Summer25/refs/heads/main/Data%20for%20Modules/Data%20For%20Intro%20to%20Categorical%20Model-Making%20Module%20by%20Austin%20Hayes/WNBA_PER_GAME_19_23_DATA.csv')

In [3]:
# Read in the WNBA 2024 data from Github
# This will be used to test the intial models 
TEST_WNBA_2024_Data = pd.read_csv('https://raw.githubusercontent.com/schuckers/Charlotte_SCORE_Summer25/refs/heads/main/Data%20for%20Modules/Data%20For%20Intro%20to%20Categorical%20Model-Making%20Module%20by%20Austin%20Hayes/2024_WNBA_Per_Game.csv')

In [4]:
# Read in the WNBA 2020-2024 data from Github 
# This dataset will be used to train the final model
TRAIN_WNBA_20_24_Data = pd.read_csv('https://raw.githubusercontent.com/schuckers/Charlotte_SCORE_Summer25/refs/heads/main/Data%20for%20Modules/Data%20For%20Intro%20to%20Categorical%20Model-Making%20Module%20by%20Austin%20Hayes/WNBA_PER_GAME_20_24_DATA.csv')

In [5]:
# Read in the current WNBA 2025 stats for our model prediction later on in this module
CURRENT_WNBA_2025_Data = pd.read_csv('https://raw.githubusercontent.com/schuckers/Charlotte_SCORE_Summer25/refs/heads/main/Data%20for%20Modules/Data%20For%20Intro%20to%20Categorical%20Model-Making%20Module%20by%20Austin%20Hayes/2025_WNBA_Per_Game.csv')

We need to scale the data in order to even the playing field among variables for model-making. This prevents a model from becoming too biased towards features or variables with larger numerical ranges. More will be explained about this during the KNN section of this model. 

In [6]:
# Make the scaler object
scaler = StandardScaler()

# Fit the scaler object to the training data for intital model-making
training_data_19_23 = scaler.fit_transform(TRAIN_WNBA_19_23_Data[['FG', 'FGA', '3P', '3PA', '2P', '2PA', 'FT', 'FTA', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']])


# SCale the test data for intial model-making
test_data_2024 = scaler.fit_transform(TEST_WNBA_2024_Data[['FG', 'FGA', '3P', '3PA', '2P', '2PA', 'FT', 'FTA', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']])


# Do the same for the other training data for final model-making
# final training data
training_data_20_24 = scaler.fit_transform(TRAIN_WNBA_20_24_Data[['FG', 'FGA', '3P', '3PA', '2P', '2PA', 'FT', 'FTA', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']])

# Scale the current 2025 WNBA data for final model-making
test_data_2025 = scaler.fit_transform(CURRENT_WNBA_2025_Data[['FG', 'FGA', '3P', '3PA', '2P', '2PA', 'FT', 'FTA', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']])

Let's get to work now! Remember, you only need to scale your predictors, not your target/variable that you are making a prediction on.

---

# Accuracy Score 

Throughout this module we will be using an accuracy score to access model prediction accuracy. An accuracy score is a metric that essentially divides the total number of correct predictions by the total amount of predictions. 

                                Total number of correct predictions by the model

                                ________________________________________________

                                Total number of predictions made by the model

---

# Logistic Regression

Logistic Regression is a categorical model that uses probabilities to predict a binary outcome. It assumes a linear relationship between independent variables. Let's go ahead and establish a logistic model and train it with the compiled 2019-2023 data.

We will train it ONLY using the neccesary stats. The model also needs to be trained using integer values, so let's keep it simple by predicting the champion based on the following stats: FG, FGA, 3P, 3PA, 2P, 2PA, FT, FTA, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS. The definitions of these variables can be found at the top of this module. 

In [7]:
# Create the logistic regression model
logistic_model = LogisticRegression()

# Train the model using the 2023 WNBA data
logistic_model.fit(training_data_19_23, TRAIN_WNBA_19_23_Data['CHAMPION'])

LogisticRegression()

In [43]:
# Have the model make predictions using the 2024 WNBA data
log_predictions = logistic_model.predict(test_data_2024)

log_predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

MMHHHMMM... very interesting! The model predicted the Las Vegas Aces as the 2024 WNBA Champions! Unfortunately, that is incorrect because the New York Liberty won the championship that season. Let's take a look at the probabilities of winning the championship based on their per game stats.

In [44]:
# Have the model show the probabilities of each team winning the championship
logistic_model.predict_proba(test_data_2024)

array([[6.16671726e-01, 3.83328274e-01],
       [8.40785596e-01, 1.59214404e-01],
       [9.90387325e-01, 9.61267471e-03],
       [9.82055176e-01, 1.79448242e-02],
       [5.77799245e-01, 4.22200755e-01],
       [9.22603451e-01, 7.73965489e-02],
       [9.90088384e-01, 9.91161563e-03],
       [9.94182691e-01, 5.81730856e-03],
       [9.96229178e-01, 3.77082188e-03],
       [9.99333418e-01, 6.66582022e-04],
       [9.99633468e-01, 3.66531969e-04],
       [9.99746067e-01, 2.53933187e-04]])

The probabilities on the left are for 0 and the right is for 1. Remember, these probabilities are in a rounded format so you can indicate where they actually are beyond the decimal point by looking at the number beyond the hyphen. We can see that the model predicted the first team in the list to have the highest odds to win the championship. The model made this decision because the predicted odds were above 50%. However, looking back at the data, the second team in the data won the championship in 2024, that team being the New York Liberty. Therefore, the second team should have the highest odds for us to feel better about this model.

Logistic regression assumes a linear relationship in the data so this may indicate that this is a poor type of model to use for this situation. For now, let's go ahead and calculate an accuracy score and move on to Discriminant Analysis Models. 

In [10]:
# Make accuracy score
accuracy_score_log = accuracy_score(TEST_WNBA_2024_Data['CHAMPION'], log_predictions)

In [11]:
# Print the accuracy score
print(f"Accuracy Score: {accuracy_score_log}")

Accuracy Score: 0.9166666666666666


---

# Discriminant Analysis


There are 2 types of Discriminant Analysis Models that we will be going over in this lesson. One is called Linear Discriminat Analysis (LDA) and the other being Quadratic Discriminant Analysis (QDA). These models essentially create a line of best fit to classify data points into a category. Discriminant Analysis finds the best combination of features through variance analysis. We will begin with LDA first.

--- 

# Linear Discriminant Analysis


LDA is a linear form of discriminant analysis and it assumes that each group follows a normal distribution. It also assumes that the variance for each classification group is the same. This means that the variance(s) between champion and non-champion is the same. Let's get started; we will follow the EXACT same process as we did with logistic regression.

In [12]:
# Create the Linear Discriminant Analysis model
lda_model = LinearDiscriminantAnalysis()

# Train the model using the 2023 WNBA data
lda_model.fit(training_data_19_23, TRAIN_WNBA_19_23_Data['CHAMPION'])

LinearDiscriminantAnalysis()

In [13]:
# Now let's test the model using the 2024 WNBA data and have it make predictions
lda_model.predict(test_data_2024)

array([1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0])

Interesting; this LDA model produced some WILD results. After scaling the predictor variables, this model has predicted several WNBA champions, which is not possible. Although this is an incorrect result that has been produced by this model, let's pursue a tie-breaker! We can do this by analyzing the probabilities among the teams predictied as champions. We will choose the winner based on the highest probability to win!

Let's take a look at the probability breakdown.

In [14]:
TEST_WNBA_2024_Data

Rk                Team   G     MP    FG   FGA    FG%    3P   3PA    3P%  \
0    1      Las Vegas Aces  40  200.6  30.9  68.1  0.454   9.4  26.5  0.355   
1    2    New York Liberty  40  200.0  30.8  68.7  0.448  10.1  29.0  0.349   
2    3       Indiana Fever  40  200.6  31.3  68.5  0.456   9.2  25.9  0.356   
3    4        Dallas Wings  40  201.9  31.7  71.0  0.446   6.3  19.2  0.326   
4    5       Seattle Storm  40  201.2  31.1  71.3  0.435   6.1  21.0  0.288   
5    6      Minnesota Lynx  40  201.9  30.1  67.3  0.448   9.5  25.0  0.380   
6    7     Phoenix Mercury  40  201.2  29.1  66.3  0.439   8.5  26.2  0.326   
7    8     Connecticut Sun  40  201.2  29.3  65.9  0.444   5.9  18.0  0.327   
8    9  Washington Mystics  40  201.2  29.0  67.0  0.433   9.7  26.6  0.366   
9   10  Los Angeles Sparks  40  200.6  28.1  66.4  0.423   7.2  22.6  0.320   
10  11         Chicago Sky  40  200.0  29.7  70.3  0.422   4.8  14.9  0.323   
11  12       Atlanta Dream  40  201.9  27.8  68.1  0.408   6.0  19.4  0.308   

    ...   ORB   DRB   TRB   AST  STL  BLK   TOV    PF   PTS  CHAMPION  
0   ...   5.6  28.5  34.1  20.5  7.1  5.0  10.8  16.5  86.4         0  
1   ...   8.5  28.1  36.6  22.8  7.9  4.5  12.7  15.4  85.6         1  
2   ...   8.3  26.8  35.1  20.4  5.9  4.3  14.2  18.2  85.0         0  
3   ...  10.5  24.3  34.8  20.4  7.1  4.0  14.8  18.5  84.2         0  
4   ...   8.7  26.0  34.7  20.7  9.3  5.2  12.4  16.5  83.2         0  
5   ...   7.4  26.8  34.3  23.0  8.6  4.2  13.4  16.4  82.0         0  
6   ...   6.7  25.6  32.3  19.9  6.6  4.7  13.3  16.9  81.5         0  
7   ...   8.4  25.1  33.5  19.9  8.2  3.7  12.1  16.1  80.1         0  
8   ...   7.1  24.8  31.9  21.6  7.3  3.4  15.1  18.4  79.3         0  
9   ...   7.4  25.3  32.7  19.7  7.3  3.2  15.0  17.9  78.4         0  
10  ...  10.9  25.8  36.6  19.0  7.0  3.8  13.1  19.0  77.4         0  
11  ...   9.2  26.9  36.1  18.4  7.2  3.7  12.5  16.9  77.0         0  

[12 rows x 26 columns]

In [15]:
# Predict the probabilities of each team winning the championship
lda_model.predict_proba(test_data_2024)

array([[0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [9.44194796e-08, 9.99999906e-01],
       [1.00000000e+00, 4.89883601e-22],
       [1.00000000e+00, 2.06095746e-10],
       [2.50888199e-12, 1.00000000e+00],
       [1.34555900e-09, 9.99999999e-01],
       [1.00000000e+00, 7.26520958e-21],
       [4.32734626e-09, 9.99999996e-01],
       [9.99999991e-01, 9.44696621e-09],
       [1.00000000e+00, 3.26906337e-38],
       [1.00000000e+00, 3.69496342e-21]])

WOW! Team number 1 (Aces), 2 (Liberty) and 6 (Lynx) all have an 100% probabiltiy to win the championship! 3-way tie! Instead, let's take a look at these teams chances to NOT be champion. Out of the 3 teams, we can exclude the Lynx because it has an extremely small chance to NOT be champion whereas the Liberty and Aces both have a 0% chance. We have a final tie between the liberty and the Aces. They each have the same probabilties to be and to NOT be champion; this makes a tie breaker extremely difficult. Although this is a last resort, we could simply look at the stats and see what team has better stats. However, that is extremely inefficient if you are working with larger datasets and should be avoided.

Let's record the accuracy score.

In [16]:
# Assign LDA Model Prediction from 2024 WNBA Data to a variable
lda_predictions = lda_model.predict(test_data_2024)

# takes a look at the array of predictions
lda_predictions

array([1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0])

In [17]:
# Get Accuracy Score
accuracy_score_lda = accuracy_score(TEST_WNBA_2024_Data['CHAMPION'], lda_predictions)

# Print the accuracy score
print(f"Accuracy Score: {accuracy_score_lda}")

Accuracy Score: 0.5833333333333334


Look at that accuracy score! That is extremely bad and this model should NOT be used for this dataset.

Let's move onto QDA!

---

# Quadratic Disciminant Analysis

QDA is very similar to LDA. QDA, like LDA, assumes a normal distribution. Unlike LDA, QDA allows each classification group to have different variances. QDA does NOT assume a linear classification boundary so it is seen as a flexible option in comparison. Now Let's get started.

NOTE: Before we get started, QDA is a bit different and needs more than one sample in the champion category. In other words, we need to add another row that has 1 under the champion column. This get's a bit hairy since we only want to include teams in the present. However, lets go ahead and do the following: Combine the 2022 and 2023 datasets.

In [18]:
# Make the Quadratic Discriminant Analysis model
qda_model = QuadraticDiscriminantAnalysis()

# Train the model using the 2023 WNBA data
qda_model.fit(training_data_19_23, TRAIN_WNBA_19_23_Data['CHAMPION'])

c:\Users\mschuck1\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\discriminant_analysis.py:1024: LinAlgWarning: The covariance matrix of class 0 is not full rank. Increasing the value of parameter `reg_param` might help reducing the collinearity.
  warnings.warn(
c:\Users\mschuck1\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\discriminant_analysis.py:1024: LinAlgWarning: The covariance matrix of class 1 is not full rank. Increasing the value of parameter `reg_param` might help reducing the collinearity.
  warnings.warn(


QuadraticDiscriminantAnalysis()

In [19]:
# Have the model make predictions using the 2024 WNBA data
qda_predictions = qda_model.predict(test_data_2024)

# takes a look at the array of predictions
qda_predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Very Interesting! This QDA Model predicted none of the teams as WNBA Champs! Let;s take a look at the probability breakdown below.

In [20]:
# Predict the probabilities of each team winning the championship
qda_model.predict_proba(test_data_2024)

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [21]:
accuracy_score_qda = accuracy_score(TEST_WNBA_2024_Data['CHAMPION'], qda_predictions)

# Print the accuracy score
print(f"Accuracy Score: {accuracy_score_qda}")

Accuracy Score: 0.9166666666666666


MMMM There might be a massive colinearity issue with using this model! It may be best to skip the use of this model! Despite this error, the accuracy score is higher for this model than the previous models!


Let's move onto KNN!

In [22]:
TRAIN_WNBA_19_23_Data

Rk                     Team   G     MP    FG   FGA    FG%    3P   3PA  \
0    1      2023 Las Vegas Aces  40  200.0  33.6  69.2  0.486   9.3  24.9   
1    2    2023 New York Liberty  40  201.9  32.2  69.9  0.460  11.1  29.7   
2    3       2023  Dallas Wings  40  200.6  32.4  73.2  0.443   6.8  21.3   
3    4     2023 Connecticut Sun  40  201.9  30.2  67.8  0.445   7.2  20.0   
4    5       2023 Atlanta Dream  40  201.3  29.4  68.7  0.428   6.4  19.2   
5    6         2023 Chicago Sky  40  201.3  30.7  69.6  0.442   8.3  22.2   
6    7       2023 Indiana Fever  40  201.9  30.2  68.3  0.442   6.7  19.8   
7    8  2023 Washington Mystics  40  200.6  28.9  67.5  0.428   7.8  23.1   
8    9      2023 Minnesota Lynx  40  201.3  29.4  67.5  0.435   6.8  20.8   
9   10  2023 Los Angeles Sparks  40  200.6  28.4  66.8  0.425   6.5  19.5   
10  11       2023 Seattle Storm  40  200.6  27.9  67.9  0.410   8.5  24.2   
11  12     2023 Phoenix Mercury  40  200.6  28.4  63.9  0.444   6.8  20.7   
12   1      2022 Las Vegas Aces  36  200.7  32.3  70.3  0.460   9.5  26.4   
13   2         2022 Chicago Sky  36  202.1  32.7  67.9  0.481   7.2  20.9   
14   3     2022 Connecticut Sun  36  201.4  31.9  69.0  0.462   6.4  18.0   
15   4        2022 Dallas Wings  36  200.7  29.7  68.2  0.435   7.8  22.6   
16   5       2022 Seattle Storm  36  200.7  30.4  68.8  0.442   9.3  25.6   
17   6      2022 Minnesota Lynx  36  201.4  30.2  67.1  0.450   6.8  19.6   
18   7     2022 Phoenix Mercury  36  202.1  28.6  66.5  0.429   8.8  26.7   
19   8  2022 Washington Mystics  36  202.1  29.3  66.8  0.439   7.6  22.5   
20   9    2022 New York Liberty  36  202.1  28.8  66.8  0.431   9.7  27.6   
21  10  2022 Los Angeles Sparks  36  200.7  29.8  66.9  0.446   5.4  16.9   
22  11       2022 Atlanta Dream  36  201.4  28.8  68.4  0.420   7.5  21.4   
23  12       2022 Indiana Fever  36  201.4  28.4  69.4  0.409   6.8  20.1   
24   1      2021 Las Vegas Aces  32  202.3  33.1  70.2  0.472   5.1  13.5   
25   2       2021 Seattle Storm  32  203.9  31.0  68.9  0.450   8.6  22.6   
26   3         2021 Chicago Sky  32  203.1  30.8  69.9  0.441   7.3  21.2   
27   4      2021 Minnesota Lynx  32  201.6  30.7  67.1  0.458   6.8  19.8   
28   5     2021 Phoenix Mercury  32  201.6  29.5  65.7  0.450   7.5  21.8   
29   6        2021 Dallas Wings  32  201.6  29.7  70.7  0.420   8.2  23.1   
30   7  2021 Washington Mystics  32  200.8  28.4  69.2  0.410   9.0  27.4   
31   8     2021 Connecticut Sun  32  201.6  29.2  65.6  0.444   7.0  19.6   
32   9       2021 Atlanta Dream  32  201.6  30.6  73.5  0.417   6.1  19.8   
33  10    2021 New York Liberty  32  200.8  28.3  66.1  0.428  10.0  27.7   
34  11       2021 Indiana Fever  32  200.0  28.4  68.2  0.417   4.9  17.3   
35  12  2021 Los Angeles Sparks  32  201.6  27.0  65.8  0.411   6.8  20.1   
36   1      2020 Las Vegas Aces  22  200.0  32.7  68.7  0.477   4.2  11.5   
37   2       2020 Seattle Storm  22  200.0  31.9  67.8  0.470   8.4  21.4   
38   3         2020 Chicago Sky  22  200.0  33.5  68.2  0.491   7.6  21.6   
39   4     2020 Phoenix Mercury  22  201.1  30.2  67.0  0.450   8.4  24.5   
40   5  2020 Los Angeles Sparks  22  202.3  32.2  67.0  0.481   7.2  18.1   
41   6      2020 Minnesota Lynx  22  200.0  30.6  67.0  0.456   8.3  21.5   
42   7        2020 Dallas Wings  22  202.3  29.5  71.0  0.415   8.9  27.6   
43   8       2020 Indiana Fever  22  200.0  29.5  66.7  0.441   6.9  20.0   
44   9       2020 Atlanta Dream  22  202.3  31.4  71.0  0.442   5.9  16.9   
45  10     2020 Connecticut Sun  22  201.1  29.7  69.5  0.427   5.9  19.0   
46  11  2020 Washington Mystics  22  202.3  29.6  68.5  0.433   8.3  24.4   
47  12    2020 New York Liberty  22  200.0  24.5  66.0  0.372   7.6  27.4   
48   1  2019 Washington Mystics  34  200.7  32.8  69.9  0.469   9.3  25.4   
49   2         2019 Chicago Sky  34  200.7  31.4  70.0  0.448   7.3  21.6   
50   3      2019 Las Vegas Aces  34  201.5  30.0  70.3  0.427   5.5  14.9   


---

# K Nearest Neigbors (KNN)



K Nearest Neighbors is a type of model that decides where to classify a data point based on the distance from previously clssified data points that the model was trained on. It is essentially deciding where to classify a data point based on the closest points or "neightbors". You can control the number of neighbors that a data point will be classified with by defining K. If you make the K number of neighbors too high, it may make the model too generalized and cause it to have low accuracy. Likewise, if you make K too small, it will be too niche and become inaccurate as well. 

Due to KNN being distance based, you will need to scale the predictor variables in order to get the best results. Scaling data points essentially levels the playing field among different measures in order to prevent the model from becoming too biased towards predictor variables with larger measures. For example, 'FGA', or 'Field Goals Attempted Per Game' will always have a larger range of numbers than 'Offensive Rebounds Per Game'

Let's test it out.

IMPORTANT RULE: For good practice, you should ONLY use odd numbers for K. This is done to prevent a tie during the prediction process. For example, if you used K=4 and there happens to be a 2-2 vote among points, it will likely result in an inaccuracte outcome. 

We will need to use standard scaler to scale the data. Let's go ahead and make the KNN model. Let's start off with K = 5 Neighbors.

In [23]:
# Make the model object for KNN with 5 neighbors
KNN_model_5 = KNeighborsClassifier(n_neighbors=5)

# Fit the model using the 2019-2023 WNBA data that was scaled earlier
KNN_model_5.fit(training_data_19_23, TRAIN_WNBA_19_23_Data['CHAMPION'])

KNeighborsClassifier()

In [24]:
# Have the model make predictions using the 2024 WNBA data
knn_predictions_5 = KNN_model_5.predict(test_data_2024)

# takes a look at the array of predictions
knn_predictions_5

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
# calculate accuracy score for KNN model with 5 neighbors
accuracy_score_knn_5 = accuracy_score(TEST_WNBA_2024_Data['CHAMPION'], knn_predictions_5)

# Print the accuracy score
print(f"Accuracy Score: {accuracy_score_knn_5}")

Accuracy Score: 0.8333333333333334


Interesting! Using 5 neighbors, this model has the same result and accuracy score as the LDA model. Now, let's do the same thing with a higher number of neigbors! Let's try a higher K of 51!

In [26]:
# Make the model object for KNN model with 51 neighbors
KNN_model_51 = KNeighborsClassifier(n_neighbors=51)

# Fit the model using the 2019-2023 WNBA data that was scaled earlier
KNN_model_51.fit(training_data_19_23, TRAIN_WNBA_19_23_Data['CHAMPION'])

KNeighborsClassifier(n_neighbors=51)

In [27]:
# Have the model make predictions using the 2024 WNBA data
knn_predictions_51 = KNN_model_51.predict(test_data_2024)

# takes a look at the array of predictions
knn_predictions_51

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
# calculate accuracy score for KNN model with 51 neighbors
accuracy_score_knn_51 = accuracy_score(TEST_WNBA_2024_Data['CHAMPION'], knn_predictions_51)

# Print the accuracy score
print(f"Accuracy Score: {accuracy_score_knn_51}")

Accuracy Score: 0.9166666666666666


Same results as the logistic model! Now let's try K = 15

In [29]:
# Make the model object for KNN model with 15 neighbors
KNN_model_15 = KNeighborsClassifier(n_neighbors=15)

# Fit the model using the 2019-2023 WNBA data that was scaled earlier
KNN_model_15.fit(training_data_19_23, TRAIN_WNBA_19_23_Data['CHAMPION'])

KNeighborsClassifier(n_neighbors=15)

In [30]:
# Have the model make predictions using the 2024 WNBA data
knn_predictions_15 = KNN_model_15.predict(test_data_2024)

knn_predictions_15

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
# calculate accuracy score for KNN model with 15 neighbors
accuracy_score_knn_15 = accuracy_score(TEST_WNBA_2024_Data['CHAMPION'], knn_predictions_15)

# Print the accuracy score
print(f"Accuracy Score: {accuracy_score_knn_15}")

Accuracy Score: 0.9166666666666666


Interesting! same results as K=51! 

Now, let's try k=13 and k=21 now!

K=13:

In [32]:
# Make the model object for KNN model with 13 neighbors
KNN_model_13 = KNeighborsClassifier(n_neighbors=13)

# Fit the model using the 2019-2023 WNBA data that was scaled earlier
KNN_model_13.fit(training_data_19_23, TRAIN_WNBA_19_23_Data['CHAMPION'])

# Have the model make predictions using the 2024 WNBA data
knn_predictions_13 = KNN_model_13.predict(test_data_2024)

knn_predictions_13

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
# calculate accuracy score for KNN model with 13 neighbors
accuracy_score_knn_13 = accuracy_score(TEST_WNBA_2024_Data['CHAMPION'], knn_predictions_13)

# Print the accuracy score
print(f"Accuracy Score: {accuracy_score_knn_13}")

Accuracy Score: 0.9166666666666666


K=21:

In [34]:
# Make the model object for KNN model with 21 neighbors
KNN_model_21 = KNeighborsClassifier(n_neighbors=21)

# Fit the model using the 2019-2023 WNBA data that was scaled earlier
KNN_model_21.fit(training_data_19_23, TRAIN_WNBA_19_23_Data['CHAMPION'])

# Have the model make predictions using the 2024 WNBA data
knn_predictions_21 = KNN_model_21.predict(test_data_2024)

knn_predictions_21

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
# calculate accuracy score for KNN model with 21 neighbors
accuracy_score_knn_21 = accuracy_score(TEST_WNBA_2024_Data['CHAMPION'], knn_predictions_21)

# Print the accuracy score
print(f"Accuracy Score: {accuracy_score_knn_21}")

Accuracy Score: 0.9166666666666666


Interesting, everything except for k=5 has produced the same results as the Logistic model!

Although our models have not produced the most ideal results, this is a part of the modeling experience. You learn what works and what does'nt. We will talk about some of these final conclusions after we make our final prediction.

Since we have a tie for the highest accuracy between the Logistic model and the KNN Model(S), let's have both of them make a prediction. Remember, we a accuracy acore cannot be predicted since the New WNBA Champion has not been decided yet. Let's try to predict who it will be!

---

# Final Predictions:

As discussed earlier, we will retrain each model in order to maintain fresh data; only keeping data from 5 seasons before the season we are predicting. We will use a different dataset that removes the 2019 data and inputs the 2024 season data that we have been making predictions on throughout this whole module. 

Let's go! We will start by making the finall logistic model

In [36]:
# Make a final Logistic model using the 2020-2024 WNBA data
logistic_model_final = LogisticRegression()

# Fit the model using the 2020-2024 WNBA data that was scaled earlier
logistic_model_final.fit(training_data_20_24, TRAIN_WNBA_20_24_Data['CHAMPION'])

# Have the model make predictions using the 2025 WNBA data
log_predictions_final = logistic_model_final.predict(test_data_2025)

log_predictions_final

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
# Key to know what team the list of probabilities is listing
CURRENT_WNBA_2025_Data

Rk                    Team   G     MP    FG   FGA    FG%    3P   3PA  \
0    1        New York Liberty  25  200.0  30.4  66.9  0.454  10.0  28.2   
1    2          Minnesota Lynx  27  200.9  31.7  68.2  0.464   9.3  26.3   
2    3      Los Angeles Sparks  26  201.0  29.7  65.3  0.455   8.7  24.7   
3    4           Indiana Fever  26  200.0  30.9  68.1  0.454   8.2  24.3   
4    5           Atlanta Dream  26  201.0  29.2  67.7  0.432   9.3  28.3   
5    6         Phoenix Mercury  25  200.0  29.8  68.8  0.433   9.7  28.6   
6    7            Dallas Wings  27  200.9  29.9  71.6  0.417   6.8  21.1   
7    8          Las Vegas Aces  27  200.0  28.3  67.3  0.420   8.1  25.1   
8    9           Seattle Storm  27  200.0  30.5  68.3  0.446   7.4  21.9   
9   10      Washington Mystics  26  201.0  28.0  64.4  0.435   5.5  16.5   
10  11  Golden State Valkyries  25  201.0  26.9  66.6  0.403   9.4  30.2   
11  12             Chicago Sky  26  200.0  28.2  67.2  0.419   7.0  20.9   
12  13         Connecticut Sun  25  200.0  26.6  65.9  0.404   6.3  20.5   

      3P%  ...    FT%   ORB   DRB   TRB   AST  STL  BLK   TOV    PF   PTS  
0   0.354  ...  0.836   7.0  27.6  34.6  21.8  8.6  5.0  12.9  16.8  87.7  
1   0.352  ...  0.790   8.3  25.7  34.1  23.6  8.2  5.1  12.3  16.9  85.9  
2   0.350  ...  0.750   8.1  25.0  33.1  20.4  7.4  2.9  14.9  18.4  84.6  
3   0.336  ...  0.771   8.3  25.4  33.7  20.2  7.8  2.9  12.9  19.3  84.4  
4   0.330  ...  0.761   8.8  27.6  36.4  20.8  6.5  4.2  11.9  16.7  83.5  
5   0.338  ...  0.773   8.6  25.6  34.2  21.0  8.4  3.8  12.5  18.7  83.1  
6   0.320  ...  0.798  11.1  25.7  36.8  20.1  7.4  4.3  13.4  19.9  82.1  
7   0.323  ...  0.831   8.1  25.4  33.5  17.7  7.2  4.7  12.6  17.7  81.6  
8   0.338  ...  0.779   6.9  24.7  31.6  21.1  8.4  4.9  12.0  17.4  80.7  
9   0.333  ...  0.749   8.7  26.5  35.2  18.7  6.5  3.0  14.8  19.4  79.1  
10  0.311  ...  0.796   9.4  26.9  36.3  18.3  7.0  2.8  14.0  18.7  78.7  
11  0.337  ...  0.775  10.1  26.2  36.2  18.7  6.8  4.0  15.9  18.9  77.1  
12  0.307  ...  0.815   8.0  22.9  30.9  16.9  7.5  3.8  13.8  20.5  74.6  

[13 rows x 25 columns]

Looks like the logistic model has predicted the New York Liberty as the 2025 WNBA Champions! 

Now, let's try a few different KNN models! We will try K=5, K=21, and K=51

K=5:

In [38]:
# Make the model object for KNN model with 5 neighbors
Final_KNN_model_5 = KNeighborsClassifier(n_neighbors=5)

# Fit the model using the 2020-2024 WNBA data that was scaled earlier
Final_KNN_model_5.fit(training_data_20_24, TRAIN_WNBA_20_24_Data['CHAMPION'])

# Have the model make predictions using the 2025 WNBA data
Final_knn_predictions_5 = Final_KNN_model_5.predict(test_data_2025)

Final_knn_predictions_5

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

K=5 Predicts the NY Liberty to win as well!

K=21:

In [39]:
# Make the model object for KNN model with 21 neighbors
Final_KNN_model_21 = KNeighborsClassifier(n_neighbors=21)

# Fit the model using the 2020-2024 WNBA data that was scaled earlier
Final_KNN_model_21.fit(training_data_20_24, TRAIN_WNBA_20_24_Data['CHAMPION'])

# Have the model make predictions using the 2025 WNBA data
Final_knn_predictions_21 = Final_KNN_model_21.predict(test_data_2025)


# takes a look at the array of predictions
Final_knn_predictions_21

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

K=51:

In [40]:
# Make the model object for KNN model with 51 neighbors
Final_KNN_model_51 = KNeighborsClassifier(n_neighbors=51)

# Fit the model using the 2020-2024 WNBA data that was scaled earlier
Final_KNN_model_51.fit(training_data_20_24, TRAIN_WNBA_20_24_Data['CHAMPION'])

# Have the model make predictions using the 2025 WNBA data
Final_knn_predictions_51 = Final_KNN_model_51.predict(test_data_2025)

# takes a look at the array of predictions
Final_knn_predictions_51

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

K=21 and K=51 did not predict any team as a champion; very interesting!


Right now we have 2 models that have predicted the Liberty as the champions!

For fun, let's have our WILD LDA model predict the champion.

In [41]:
# Make the model object for the final LDA model
Final_LDA_model = LinearDiscriminantAnalysis()

# Fit the model using the 2019-2023 WNBA data that was scaled earlier
Final_LDA_model.fit(training_data_20_24, TRAIN_WNBA_20_24_Data['CHAMPION'])

# Have the model make predictions using the 2025 WNBA data
Final_LDA_model_predictions = Final_LDA_model.predict(test_data_2025)

Final_LDA_model_predictions

array([1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0])

Once again, it has predicted multiple champions! Let's do a tie breaker once again by looking at the probabilities!

In [42]:
Final_LDA_model.predict_proba(test_data_2025)

array([[1.07696074e-11, 1.00000000e+00],
       [9.99999617e-01, 3.82701944e-07],
       [9.99979491e-01, 2.05090367e-05],
       [9.99999959e-01, 4.12466314e-08],
       [4.42792247e-10, 1.00000000e+00],
       [6.46543927e-02, 9.35345607e-01],
       [9.99999756e-01, 2.44415379e-07],
       [4.35676143e-01, 5.64323857e-01],
       [1.00000000e+00, 3.78048485e-16],
       [9.99999850e-01, 1.50137601e-07],
       [1.04294351e-12, 1.00000000e+00],
       [9.65252357e-01, 3.47476435e-02],
       [1.00000000e+00, 1.64224957e-15]])

The First team, fifth team and eleventh teams all have the highest probabilities! We have another tie but this time each have 100% odds of being champion! On top of the tie breaker we are already doing, lets break the tie by analyzing which team, among those 3, has the LOWEST odds of NOT being champion. It looks like the eleventh team has the lowest probability to NOT be champion. Therefore, we will conclude that this team will be this models predicted champion. If we go back and check the dataframe, we can see that the eleventh team is the brand new expansion team, the Golden State Valkyries!

The LDA model has predicted the Golden State Valkyries has the 2025 WNBA Champions!

---

# Final Conclusions


Throughout this module, we have seen a lot of things. We have gone over the basics of modeling with KNN, LDA, QDA and Logistic models. We have discussed scaling, accuracy scores, tie-breakers, etc. There is a LOT that comes with the modeling process. There are also lots of other types of models that could have been used to find this outcome such as SVM's, Decision Trees, etc. There are plenty of other alternatives that could be used in place of the models we have learned about today. 

We learned that Discriminant Analysis was NOT a good idea for this dataset and that logistic models, along with KNN models, fit this project much better. This may be due to the scaling along with the variances/relationships among the predictor variables. Exploratory analysis and data validation is extremely important in the model-making process. Preparing the data for usage and discovering what works and what does'nt is a vital piece of the puzzle, as we figured out today. 

Despite the failures using Discriminant Analysis models, our Logistic and KNN Models produced consistant results among their predictions. After modeling the results, we will conclude that the New York Liberty will go back to back and win the 2025 WNBA championship!

---

# Review Questions

Below, you will be asked a series of questions to review the material you have learned throughout this module.

### 1.) How does KNN work and what needs to be done to the data before use of a KNN model?

### 2.) Using the 2020-2024 dataset, create a list of predictor variables that include FG%, 3P%, 2P%, FT%, ORB, AST. Scale the list of predictor variables. Make sure you also scale them for the 2025 data since you will be asked to make a prediction on them later. Create a new column in the ORIGINAL 2020-2024 dataset that assesses whether a teams points ('PTS') are over 85 per game. 1 = True, 0 = False. Make this column for the ORIGINAL 2025 dataset as well. 

Hint: _Use .astype(int)_ 

### 3.) Using the scaled data you created in question 2, predict whether a team(s) will have above 85 points per game during the 2025 WNBA season with a QDA model. Record an accuracy score. 

QUICK NOTE: You can use an accuracy score in this case because there are already pts per game recorded for each team thus far. Although they are not final for the WHOLE season, this is an interesting experiment to see if these are strong predictors of whether a team will have high points per game. 

### 4.) Do the same thing you did in question 3 but with 3 KNN models instead. Use K=5, K=25 and K=51 respectively. Record an accuracy score.

### 5.) As you did in questions 3 and 4, make a prediction but use a Logistic model instead. Record an accuracy score.

### 6.) Which model(s) had the highest accuracy score? Is there a tie between the most accurate models? Or is there a model that is clearly the best in terms of an accuracy score?

### 7.) What differentiates LDA and QDA? List a few differences.